# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - whisper-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockernihal.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9fe89de3585242c3a0fc68577051e848 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ef91099378c1419eb59d8bd53bfb2c87 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockernihal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9fe89de3585242c3a0fc68577051e848 }}/testdockernihal/whisper-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'whisper-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3121037268884284ab9a8d25d4f373f8 }}
        images: 'testdockernihal.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9fe89de3585242c3a0fc68577051e848 }}/testdockernihal/whisper-api:${{ github.sha }}'